/* SIMPLIFY dict: fancy word -> simple ("ten hundred") swap.
   Loaded before the page script (sets window.__SIMPLIFY). Keys were seeded by
   running SmolLM2 (transformers.js, in Node) and Chrome's Gemini Nano over many
   concepts and collecting the fancy words they reach for; every replacement
   value is word(s) from the ten-hundred list (words.js). Sorted A-Z for reading.
   903 entries. */
(typeof globalThis !== "undefined" ? globalThis : window).__SIMPLIFY = {
  abilities: "powers",
  ability: "power",
  abstract: "not real to touch",
  abstraction: "an idea with no real thing",
  abundant: "lots",
  accelerate: "gets faster",
  acceleration: "gets faster",
  accordingly: "so",
  accumulate: "pile up",
  accurate: "right",
  accurately: "the right way",
  acoustic: "about sound",
  acoustics: "study of sound",
  acquire: "get",
  acquired: "got",
  adapt: "change to fit",
  adaptation: "changing to fit",
  additional: "more",
  advanced: "far along",
  advice: "help",
  affect: "change",
  affects: "changes",
  aggregate: "put together",
  algorithm: "set of steps",
  algorithms: "sets of steps",
  allocate: "give out",
  allows: "lets",
  alters: "changes",
  amazing: "so good",
  ambiguity: "not being clear",
  ambiguous: "not clear",
  amount: "how much",
  analyse: "look at",
  analysis: "close look",
  analyze: "look at",
  anatomy: "study of the body",
  ancestor: "one who came long before",
  ancestors: "ones who came long before",
  angle: "way",
  angles: "ways",
  apart: "away from each other",
  apparent: "clear to see",
  apply: "use",
  approximate: "about",
  approximately: "about",
  arbitrary: "picked with no reason",
  arrange: "put in order",
  arranging: "sorting",
  articulate: "say clearly",
  artificial: "made by people",
  artist: "a person who makes art",
  artists: "people who make art",
  aspect: "part",
  aspects: "parts",
  assemble: "put together",
  assess: "work out how good",
  assignment: "school work",
  assignments: "school work",
  associate: "join together",
  assumes: "takes as true",
  astronomy: "study of the stars",
  asymmetry: "not the same on both sides",
  atom: "tiny bit",
  atomic: "about tiny bits",
  atoms: "tiny bits",
  attention: "looking hard",
  automatically: "on its own",
  autonomous: "on its own",
  average: "the middle number",
  awareness: "knowing it is there",
  backwards: "back to front",
  balance: "staying even",
  balanced: "even",
  band: "a ring",
  battery: "a thing that holds power",
  bead: "a little round ball",
  beads: "little round balls",
  behave: "act",
  behavior: "how it acts",
  behaviors: "how they act",
  behaviour: "how it acts",
  berries: "small round sweet foods",
  biological: "about living things",
  biology: "study of living things",
  bizarre: "very funny",
  blink: "close and open your eyes fast",
  blinked: "closed and opened your eyes fast",
  blinking: "when your eyes open and close fast",
  bounce: "jump back",
  bouncy: "jumps back",
  boundary: "edge",
  bowl: "a deep round thing to hold food",
  brick: "a hard block",
  bricks: "hard blocks",
  bubbly: "full of tiny air balls",
  bump: "a small hit",
  bumping: "hitting into things",
  bumps: "small hits",
  bunch: "a lot",
  bureaucracy: "many laws and slow steps",
  cabinet: "a box to keep things in",
  calculate: "work out",
  calculates: "works out",
  calculating: "working out",
  calculation: "working out",
  capability: "what it can do",
  capacity: "how much it can hold",
  cascade: "step after step",
  cascades: "step after step",
  catalyst: "thing that makes it go faster",
  categories: "groups",
  categorize: "sort",
  category: "group",
  cause: "reason",
  causes: "reasons",
  cease: "stop",
  cell: "tiny bit",
  cells: "tiny bits",
  cellular: "about tiny bits",
  chaos: "trouble",
  chaotic: "wild",
  cheer: "a happy shout",
  chemical: "stuff",
  chemicals: "stuff",
  chemistry: "study of stuff",
  chew: "eat slowly",
  circuit: "power path",
  circumstance: "how things are",
  classification: "sorting",
  classify: "sort",
  clever: "good at thinking",
  click: "a small sound",
  clock: "a thing that tells time",
  closely: "up close",
  clue: "a bit that helps you find out",
  clues: "bits that help you find out",
  code: "steps for a machine",
  coefficient: "number in front",
  cognition: "thinking",
  cognitive: "about thinking",
  combinatorial: "about how things go together",
  combine: "put together",
  combined: "put together",
  combines: "puts together",
  combining: "putting together",
  commence: "start",
  communicate: "talk",
  communication: "talking",
  comparatively: "next to others",
  complete: "finish",
  complex: "hard",
  complexity: "how hard it is",
  complicated: "hard",
  component: "part",
  components: "parts",
  compound: "joined stuff",
  comprehend: "understand",
  comprehends: "gets",
  comprise: "be made of",
  computational: "about working out",
  compute: "work out",
  "computer program": "steps for a machine",
  conceal: "hide",
  concept: "idea",
  concepts: "ideas",
  concerning: "about",
  conclude: "end",
  concluded: "worked out",
  concrete: "real to touch",
  condition: "how it is",
  conditions: "how things are",
  cone: "a shape with a point",
  connect: "join",
  connected: "joined",
  connection: "way things join",
  connections: "ways things join",
  consciousness: "knowing you are here",
  consequence: "what comes after",
  consequences: "what comes after",
  consequently: "so",
  considerable: "big",
  considerably: "a lot",
  consist: "be made of",
  consistent: "the same each time",
  constant: "always the same",
  constitute: "make up",
  constraint: "how far it can go",
  construct: "build",
  contain: "hold",
  contains: "holds",
  context: "what is around it",
  continuum: "one long line",
  controls: "is in control of",
  convergence: "coming together",
  conversion: "change",
  convert: "change",
  convey: "get across",
  cookie: "a sweet flat food",
  cookies: "sweet flat foods",
  correlate: "go along with",
  correlation: "how things go together",
  cosmic: "about space",
  crash: "hit hard",
  creates: "makes",
  creation: "making",
  creator: "maker",
  creators: "makers",
  crimes: "bad things people do",
  crucial: "very needed",
  crunchy: "hard and loud to eat",
  curious: "wanting to know",
  curiousness: "wanting to know",
  customer: "buyer",
  customers: "buyers",
  cybernetics: "study of control",
  cycle: "round and round",
  cycles: "round and round",
  data: "facts",
  decision: "choice",
  decisions: "choices",
  decrease: "go down",
  deficit: "too little",
  deliberate: "done for a reason",
  demonstrate: "show",
  demonstrated: "showed",
  denote: "mean",
  denotes: "means",
  density: "how full of stuff",
  depending: "going by",
  depends: "goes by",
  derivative: "how fast something changes",
  derive: "come from",
  derived: "came from",
  design: "plan out",
  designed: "made to",
  designing: "making a plan for",
  desirable: "wanted",
  desireable: "wanted",
  detailed: "full of small parts",
  detective: "a person who finds out who did it",
  detects: "finds",
  determine: "decide",
  determined: "decided",
  determines: "decides",
  develop: "grow",
  development: "growing",
  device: "machine",
  devices: "machines",
  dice: "little blocks you roll",
  differentiate: "know one from the other",
  differently: "in a different way",
  diffusion: "spreading out",
  digital: "about numbers",
  dimension: "a way to size things",
  dimensions: "ways to size things",
  diminish: "get smaller",
  disagree: "not agree",
  disperse: "spread out",
  display: "show",
  distinct: "clearly not the same",
  distinguish: "know one from the other",
  distribute: "spread out",
  diverse: "of many kinds",
  doctrine: "set of beliefs",
  dots: "small round marks",
  doughnut: "round food",
  downhill: "down a hill",
  duality: "being two things at once",
  duper: "really good",
  dynamic: "moving",
  ecological: "about the world",
  ecology: "study of the world",
  economic: "about money",
  economics: "study of money",
  economies: "money worlds",
  economy: "money world",
  edible: "safe to eat",
  effect: "what it does",
  effects: "what they do",
  efficient: "fast",
  efficiently: "fast",
  elaborate: "full of parts",
  electrical: "about power",
  electricity: "power",
  electron: "tiny bit",
  electronics: "study of small power",
  electrons: "tiny bits",
  element: "part",
  elements: "parts",
  eliminate: "get rid of",
  emerge: "come out",
  emergence: "popping up",
  emergent: "popping up",
  emotion: "feeling",
  emotions: "feelings",
  empirical: "from looking",
  employ: "use",
  enable: "let",
  enables: "lets",
  encouragement: "words that help you keep going",
  energy: "power",
  engineers: "people who build things",
  enhance: "make better",
  enormous: "huge",
  environment: "world around",
  epistemic: "about knowing",
  equation: "a way to work out numbers",
  equilibrium: "even and still",
  equivalent: "the same",
  essential: "needed",
  essentially: "really",
  establish: "set up",
  estimate: "guess",
  estimation: "guess",
  estimations: "guesses",
  evaluate: "work out how good",
  eventual: "in the end",
  evident: "easy to see",
  evolution: "slow change",
  evolve: "slowly change",
  exactly: "just right",
  examine: "look at",
  example: "like this",
  examples: "like this",
  excess: "too much",
  exclude: "leave out",
  exhibit: "show",
  exhibited: "showed",
  existence: "being real",
  explicit: "very clear",
  exploration: "looking around",
  express: "say",
  extends: "goes on",
  extract: "pull out",
  extraordinary: "very special",
  fabricate: "make up",
  facilitate: "help",
  factor: "thing that helps",
  factors: "things that help",
  favorite: "the one you like best",
  feature: "part",
  features: "parts",
  filing: "putting papers away",
  "filing cabinet": "a place to keep papers",
  flexible: "easy to bend",
  floating: "moving in the air",
  floaty: "light in the air",
  fluid: "stuff that moves like water",
  fluids: "stuff that moves like water",
  flux: "always changing",
  folks: "people",
  force: "push or pull",
  forensics: "finding out what happened",
  formation: "making",
  formula: "a set way to work it out",
  formulate: "work out",
  fort: "a safe place",
  fraction: "part",
  framework: "the main parts",
  frequencies: "how often",
  frequency: "how often",
  friendship: "being friends",
  function: "job",
  functional: "about the job it does",
  functions: "jobs",
  fundamental: "main",
  fundamentally: "at heart",
  furthermore: "and also",
  generate: "make",
  generated: "made",
  generates: "makes",
  generating: "making",
  generation: "making",
  generic: "not special",
  genetics: "study of how living things pass things on",
  geological: "about rocks",
  geology: "study of rocks",
  geometry: "study of shapes",
  giant: "huge",
  goggles: "eye glasses",
  governance: "who is in control",
  governs: "is in control of",
  grades: "school marks",
  gradient: "how much it goes up",
  grain: "a tiny bit",
  gravity: "pull down",
  growth: "growing",
  grumpy: "cross and mad",
  harmonic: "even",
  harmonics: "even sounds",
  helpful: "a big help",
  hence: "so",
  hierarchical: "in a top-down order",
  hierarchy: "order from top to bottom",
  homeostasis: "staying the same",
  homework: "school work",
  hooked: "caught on",
  however: "but",
  hug: "hold close with your arms",
  humming: "a soft low sound",
  hypothesis: "a guess",
  hypothesized: "guessed",
  "ice cream": "a cold sweet food",
  identical: "the very same",
  identify: "pick out",
  illustrate: "show",
  imagination: "making up ideas in your head",
  imbalance: "not even",
  immense: "huge",
  impact: "hit",
  implement: "put to work",
  implicit: "not said out loud",
  implies: "points to",
  improve: "make better",
  improvement: "getting better",
  include: "take in",
  incorporate: "take in",
  increase: "go up",
  indeed: "for real",
  indicate: "show",
  indicates: "shows",
  individuals: "people",
  inference: "working out",
  infinite: "with no end",
  infinity: "no end",
  influence: "power to change things",
  influences: "changes the way of",
  info: "facts",
  informatics: "study of facts",
  information: "facts",
  inherently: "by itself",
  initial: "first",
  initiate: "start",
  instinct: "born knowing",
  institution: "big group",
  institutions: "big groups",
  instructions: "steps",
  integrate: "join up",
  intelligence: "how good at thinking",
  intelligent: "good at thinking",
  interact: "work with each other",
  interpret: "work out the meaning",
  interpretive: "about meaning",
  interprets: "works out",
  intricate: "hard",
  intrinsically: "deep down",
  intuition: "knowing with no reason",
  inventors: "people who make new things",
  investigate: "look into",
  invisible: "can not be seen",
  involve: "take part",
  involved: "taking part",
  item: "thing",
  items: "things",
  iterate: "do it again",
  iteration: "one more try",
  keyhole: "key hole",
  kindness: "being kind",
  knowledge: "things we know",
  lego: "a thing you build with",
  legos: "things you build with",
  limitation: "how far it can go",
  linguistics: "study of words",
  linked: "joined together",
  loose: "free to move",
  lunchbox: "a box for lunch",
  magic: "make-believe powers",
  magnet: "pulling stone",
  magnetic: "about pulling power",
  magnetism: "pulling power",
  magnets: "pulling stones",
  magnitude: "how big",
  maintain: "keep up",
  majority: "most",
  manufacture: "make",
  mass: "how much stuff",
  matches: "is the same",
  material: "stuff",
  materials: "stuff",
  math: "numbers",
  mathematicians: "number people",
  mathematics: "numbers",
  maximize: "make the most",
  maximum: "most",
  measure: "find the size of",
  measurement: "size",
  measurements: "sizes",
  mechanical: "about machines",
  mechanism: "how it works",
  mechatronics: "machine parts",
  median: "the middle one",
  medicine: "cure",
  medicines: "cures",
  memory: "what you keep in your head",
  messy: "all over the place",
  metabolic: "about body power",
  metabolism: "how the body burns food",
  metallurgical: "about metal",
  metallurgist: "metal person",
  metallurgists: "metal people",
  metallurgy: "study of metal",
  method: "way",
  methods: "ways",
  microscope: "tiny-thing glass",
  minimize: "make the least",
  minimum: "least",
  minority: "the few",
  mistakes: "things done wrong",
  mix: "put together",
  mixed: "put together",
  mixes: "puts together",
  mixing: "putting together",
  model: "a way to show a thing",
  modification: "change",
  modify: "change",
  module: "part",
  molecular: "about tiny bits",
  molecule: "tiny bit",
  molecules: "tiny bits",
  momentum: "push",
  monitors: "watches",
  moreover: "and also",
  motion: "moving",
  movement: "moving",
  multi: "many",
  multiple: "many",
  muscle: "body part",
  mysteries: "things no one can figure out",
  natural: "from the world",
  nature: "the world",
  nearby: "close by",
  neat: "nice",
  negligible: "very small",
  nerve: "body part",
  nerves: "body parts",
  network: "things joined up",
  networks: "things joined up",
  neurological: "about the brain",
  neuron: "brain bit",
  neurons: "brain bits",
  nevertheless: "even so",
  nicely: "in a nice way",
  noisy: "loud",
  nothingness: "empty space",
  notion: "idea",
  nudge: "a little push",
  numerical: "about numbers",
  numerous: "many",
  nuts: "hard little foods you eat",
  object: "thing",
  objects: "things",
  obscure: "hard to see",
  observe: "watch",
  observes: "watches",
  obtain: "get",
  obtained: "got",
  obvious: "easy to see",
  occurrence: "happening",
  ocean: "sea",
  offers: "gives",
  optical: "about light",
  optics: "study of light",
  optimal: "best",
  optimise: "make best",
  optimization: "best way",
  optimizations: "best ways",
  optimize: "make best",
  optimum: "best",
  orderly: "in order",
  ordinary: "not special",
  organism: "living thing",
  organisms: "living things",
  organize: "put in order",
  organized: "put in order",
  origin: "start",
  oscillate: "move over and over",
  outcome: "end",
  outcomes: "ends",
  outsmart: "beat",
  overcome: "get past",
  overflowing: "so full it comes out",
  owes: "should pay back",
  pancake: "a flat round food",
  pancakes: "flat round food",
  paradigm: "way of seeing",
  parameter: "setting",
  parameters: "settings",
  particle: "tiny bit",
  particles: "tiny bits",
  particular: "special",
  pathways: "ways to go",
  pattern: "shape",
  patterns: "shapes",
  pebble: "tiny rock",
  peculiar: "funny",
  perceive: "see",
  perceives: "sees",
  percentage: "out of a hundred",
  perception: "seeing and hearing",
  perceptual: "about seeing",
  permanent: "for always",
  persistent: "keeping on",
  petrol: "car power",
  phase: "step",
  phases: "steps",
  phenomena: "things that happen",
  phenomenon: "thing that happens",
  philosophy: "deep thinking",
  physics: "study of how things move",
  planet: "world",
  planetary: "about worlds",
  planets: "worlds",
  playground: "play place",
  plus: "also",
  poke: "push",
  possibilities: "the many ways",
  possibility: "maybe",
  potential: "could-be power",
  practical: "real world",
  precise: "just right",
  precisely: "just right",
  predict: "guess",
  predictable: "easy to guess",
  predicting: "guessing",
  prediction: "guess",
  predictions: "guesses",
  predicts: "guesses",
  predominantly: "mostly",
  preserve: "keep safe",
  pressure: "push",
  primarily: "mostly",
  primary: "main",
  primitive: "very old and simple",
  principal: "main",
  principle: "main law",
  principles: "main laws",
  prism: "clear glass that bends light",
  probabilistic: "about chance",
  probability: "chance",
  procedure: "steps",
  process: "steps",
  processes: "steps",
  produce: "make",
  produces: "makes",
  program: "steps for a machine",
  propagate: "spread",
  properly: "the right way",
  properties: "what they are like",
  property: "what it is like",
  proportion: "share",
  proposed: "put forward",
  proposes: "puts forward",
  protein: "body building stuff",
  provides: "gives",
  psychology: "study of the mind",
  purpose: "reason",
  purposes: "reasons",
  puzzle: "brain game",
  puzzles: "brain games",
  quantities: "how much",
  quantity: "how much",
  radiation: "power waves",
  rainbow: "the colors in the sky after rain",
  randomness: "happening by chance",
  range: "how far it goes",
  ratio: "how many for each",
  rationale: "the reason",
  reasoning: "working things out",
  recipe: "steps to make food",
  recipes: "ways to make food",
  recognize: "know again",
  recursion: "over and over",
  recursive: "over and over",
  redesigning: "making a new plan for",
  reduce: "make less",
  refer: "mean",
  referential: "pointing back",
  referring: "pointing",
  refers: "means",
  reflects: "shows",
  regarding: "about",
  regenerate: "grow back",
  regulates: "keeps in check",
  relationship: "way things go",
  relationships: "ways things go",
  relatively: "pretty",
  relativistic: "about fast moving things",
  remarkable: "very good",
  remove: "take away",
  represent: "stand for",
  representation: "a picture that stands for it",
  represented: "stood for",
  representing: "standing for",
  represents: "stands for",
  require: "need",
  requires: "needs",
  resonance: "ringing together",
  restart: "start over",
  result: "what comes out",
  results: "what come out",
  retain: "keep",
  reveal: "show",
  revolve: "go around",
  rigid: "very hard",
  robot: "a machine",
  robotics: "study of machines",
  robots: "machines",
  rockets: "machines that fly to space",
  role: "job",
  roles: "jobs",
  rotate: "spin",
  roughly: "about",
  route: "the way you go",
  rubber: "stuff you can bend",
  "rubber band": "a thing you can stretch",
  rule: "law",
  rules: "laws",
  scarce: "not much",
  scenario: "what might happen",
  scientist: "people who study things",
  scientists: "people who study things",
  secondary: "second",
  secret: "kept hidden",
  secrets: "things kept hidden",
  seesaw: "an up and down thing",
  semantic: "about meaning",
  semantics: "word meaning",
  sentence: "a group of words",
  sentences: "groups of words",
  sentience: "being able to feel",
  separate: "put in two groups",
  separately: "on its own",
  sequence: "order",
  sequences: "orders",
  shrinks: "gets smaller",
  shuffle: "put in a new order",
  shuffled: "put in a new order",
  signal: "sign",
  signals: "signs",
  significant: "big",
  significantly: "a lot",
  signify: "mean",
  similar: "close to the same",
  simultaneously: "at the same time",
  situation: "how things are",
  skill: "a thing you can do",
  skills: "things you can do",
  skip: "jump over",
  smart: "good at thinking",
  smarter: "better at thinking",
  smooth: "flat",
  snack: "a bit of food",
  sneaky: "trying not to be seen",
  snowball: "a ball of snow",
  society: "people",
  sociology: "study of people",
  solar: "about the sun",
  solve: "work out",
  solved: "worked out",
  solving: "working out",
  sophisticated: "very hard to make",
  spark: "a tiny flash of light",
  sparkles: "gives off tiny lights",
  sparkly: "full of light",
  spatial: "about space",
  speciation: "making new kinds",
  specific: "special",
  speck: "tiny bit",
  spectra: "many kinds",
  spectrum: "many kinds",
  sphericity: "how round it is",
  spontaneous: "on its own",
  sprinkles: "tiny bits on top",
  squishy: "soft",
  stable: "staying the same",
  stack: "a pile",
  stacked: "put in a pile",
  stacks: "piles",
  stage: "step",
  stages: "steps",
  static: "still",
  statistics: "study of numbers",
  steady: "not moving much",
  stochastic: "not the same each time",
  string: "a thin line",
  structural: "about shape",
  structure: "shape",
  structures: "shapes",
  stubborn: "will not give in",
  subsequent: "next",
  subsequently: "after that",
  substance: "stuff",
  substances: "stuff",
  substantial: "big",
  substantially: "a lot",
  sufficient: "enough",
  suggests: "points to",
  "sun's": "sun",
  sunshine: "sun light",
  super: "very",
  superhero: "a person with special powers",
  surplus: "extra",
  sustain: "keep going",
  switch: "turn on or off",
  switches: "turns on and off",
  symbol: "sign",
  symbolize: "stand for",
  symbols: "signs",
  symmetry: "same on both sides",
  synthesis: "making one from many",
  synthesize: "make one from many",
  system: "set of things",
  systematic: "in order",
  systems: "sets of things",
  tag: "a small sign",
  tastes: "how food is in your mouth",
  tasty: "good to eat",
  technique: "way",
  techniques: "ways",
  technologies: "machines",
  technology: "machines",
  telescope: "star glass",
  telescopes: "star glasses",
  temperature: "how hot",
  temporal: "about time",
  temporary: "not for long",
  terminate: "end",
  theoretical: "only an idea",
  theories: "ideas",
  theory: "idea",
  therefore: "so",
  thermal: "about heat",
  thermodynamics: "study of heat",
  threshold: "the point it starts",
  thus: "so",
  tidy: "in order",
  tight: "close together",
  tissue: "body stuff",
  tons: "a lot",
  tool: "a thing you use for a job",
  tools: "things you use for a job",
  topological: "about how shapes join",
  tower: "a tall building",
  towers: "tall buildings",
  toy: "a play thing",
  toys: "play things",
  trade: "give and get",
  trajectories: "paths",
  trajectory: "path",
  transform: "change",
  transformation: "big change",
  transition: "change",
  transmit: "send",
  tremendous: "huge",
  trick: "a special way to do it",
  trickier: "harder to do",
  tricks: "special ways to do things",
  tricky: "hard",
  tummy: "where food goes",
  typical: "usual",
  typically: "usually",
  ultimate: "last",
  uncertainty: "not being sure",
  underwater: "under water",
  uniform: "all the same",
  unique: "one of a kind",
  unit: "part",
  units: "parts",
  universe: "all of space and everything in it",
  unpredictable: "hard to guess",
  unstable: "not staying the same",
  unusual: "not usual",
  useful: "a big help",
  utilise: "use",
  utilize: "use",
  utilized: "used",
  vague: "not clear",
  variable: "changing",
  variance: "how spread out",
  various: "many",
  vast: "huge",
  vehicle: "a thing you ride in",
  vehicles: "things you ride in",
  velocity: "how fast",
  version: "kind",
  "very-duper": "so very good",
  vibrate: "shake",
  vibration: "shaking",
  vibrations: "shaking",
  virtual: "not really there",
  visual: "about seeing",
  vital: "very needed",
  voltage: "push of power",
  warmth: "being warm",
  wavelength: "wave size",
  weird: "funny",
  wiggle: "move side to side",
  wire: "a thin metal line",
  wizards: "people with special powers",
  wonderful: "so good",
  wrongness: "being wrong",
  yields: "gives",
  yummy: "good to eat"
};
